Add anti spam plugin
clragon/swan pull request #13
Opened 2023-11-27 19:50 UTC by abitofevrything

Closes #4.

I didn't add cache cleanup since we store at most 5 messages per channel, and that's not going to consume any important amount of memory.

2023-11-28 00:27 UTC, clragon requested changes

2023-11-28 00:27 UTC, clragon commented on lib/plugins/anti_spam/plugin.dart
> +          await event.guild!.createBan(
we probably wanna add a check here if the bot actually has ban permissions. 
otherwise, we could just omit this part.

2023-11-28 00:27 UTC, clragon commented on lib/plugins/anti_spam/plugin.dart
> +            deleteMessages: const Duration(days: 7),
not sure if we want to delete all their messages. maybe 1 hour is fine?

2023-11-28 00:27 UTC, clragon commented on lib/plugins/anti_spam/plugin.dart
> +            (await channel.messages.fetchMany(limit: cacheSize)).map(
this runs into permission issues

2023-11-28 00:27 UTC, clragon commented on lib/plugins/anti_spam/plugin.dart
> +    client.onMessageCreate.listen((event) async {
we should exclude bots and admins from the get go

2023-11-28 00:27 UTC, clragon commented on lib/plugins/database.dart
> +final database = SwanDatabase();
global variable bad, plugin locator good

2023-11-28 00:27 UTC, clragon commented on lib/plugins/anti_spam/plugin.dart
> +}
could this be part of nyxx? 🤔

2023-11-28 15:33 UTC, abitofevrything commented on lib/plugins/anti_spam/plugin.dart
> +}
It.... could be. But it isn't for now, so we'll just have to implement it ourselves.

2023-11-29 10:21 UTC, clragon approved these changes

2023-11-29 10:22 UTC, merged